### ISSUE TITLE
Error in R509::CertificateAuthority::HTTP::Server for get '/1/crl/:ca/get/?' - undefined method 'to_pem'

### ISSUE THREAD

**Issue by ghost** [r509/r509-ca-http#18]
NoMethodError: undefined method `to_pem' for #<R509::CRL::Administrator... for /1/crl/:ca/get. Fix: crl(params[:ca]).crl.to_pem

**Comment by reaperhulk** [comment]
Thanks for the bug report!

In the latest pre-release r509 (which r509-ca-http has been updated to be compatible with) this method has been deprecated (because we no longer retain the generated CRL in CRL::Administrator), but your fix is perfect for the existing release. BTW, I hang out in #r509 on irc.freenode.net if you ever need support/want to complain about the API.

**Comment by reaperhulk** [comment]
See: https://github.com/reaperhulk/r509-ca-http

This will be merged back into master soon.

**Comment by ghost** [comment]
Thanks.
